apiVersion: v1
kind: Service
metadata:
  name: cognitive-luis-svc-nodeport
spec:
  selector:
    app: cognitive-luis
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: http-port
    port: 5000
    nodePort: 31234
